<?php
/**
 * Locale data for 'uk'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2011 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '6546',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => ',',
    'group' => ' ',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'Не число',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '#,##0.00 ¤',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => '¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => '$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'AZN' => 'ман.',
    'RSD' => 'дин.',
    'RUB' => 'руб.',
    'UAH' => '₴',
    'UAK' => 'крб.',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'січня',
      2 => 'лютого',
      3 => 'березня',
      4 => 'квітня',
      5 => 'травня',
      6 => 'червня',
      7 => 'липня',
      8 => 'серпня',
      9 => 'вересня',
      10 => 'жовтня',
      11 => 'листопада',
      12 => 'грудня',
    ),
    'abbreviated' => 
    array (
      1 => 'січ.',
      2 => 'лют.',
      3 => 'бер.',
      4 => 'квіт.',
      5 => 'трав.',
      6 => 'черв.',
      7 => 'лип.',
      8 => 'серп.',
      9 => 'вер.',
      10 => 'жовт.',
      11 => 'лист.',
      12 => 'груд.',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'С',
      2 => 'Л',
      3 => 'Б',
      4 => 'К',
      5 => 'Т',
      6 => 'Ч',
      7 => 'Л',
      8 => 'С',
      9 => 'В',
      10 => 'Ж',
      11 => 'Л',
      12 => 'Г',
    ),
    'abbreviated' => 
    array (
      1 => 'Січ',
      2 => 'Лют',
      3 => 'Бер',
      4 => 'Кві',
      5 => 'Тра',
      6 => 'Чер',
      7 => 'Лип',
      8 => 'Сер',
      9 => 'Вер',
      10 => 'Жов',
      11 => 'Лис',
      12 => 'Гру',
    ),
    'wide' => 
    array (
      1 => 'Січень',
      2 => 'Лютий',
      3 => 'Березень',
      4 => 'Квітень',
      5 => 'Травень',
      6 => 'Червень',
      7 => 'Липень',
      8 => 'Серпень',
      9 => 'Вересень',
      10 => 'Жовтень',
      11 => 'Листопад',
      12 => 'Грудень',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Неділя',
      1 => 'Понеділок',
      2 => 'Вівторок',
      3 => 'Середа',
      4 => 'Четвер',
      5 => 'Пʼятниця',
      6 => 'Субота',
    ),
    'abbreviated' => 
    array (
      0 => 'Нд',
      1 => 'Пн',
      2 => 'Вт',
      3 => 'Ср',
      4 => 'Чт',
      5 => 'Пт',
      6 => 'Сб',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'Н',
      1 => 'П',
      2 => 'В',
      3 => 'С',
      4 => 'Ч',
      5 => 'П',
      6 => 'С',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'до н.е.',
      1 => 'н.е.',
    ),
    'wide' => 
    array (
      0 => 'до нашої ери',
      1 => 'нашої ери',
    ),
    'narrow' => 
    array (
      0 => 'до н.е.',
      1 => 'н.е.',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y \'р\'.',
    'long' => 'd MMMM y \'р\'.',
    'medium' => 'd MMM y',
    'short' => 'dd.MM.yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'HH:mm:ss zzzz',
    'long' => 'HH:mm:ss z',
    'medium' => 'HH:mm:ss',
    'short' => 'HH:mm',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'дп',
  'pmName' => 'пп',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'aa' => 'афарська',
    'ab' => 'абхазька',
    'ace' => 'ачехська',
    'ach' => 'ачолі',
    'ada' => 'адангме',
    'ady' => 'адигейська',
    'ae' => 'авестійська',
    'af' => 'африкаанс',
    'afa' => 'афро-азійська мова',
    'afh' => 'африхілі',
    'ain' => 'айнська',
    'ak' => 'акан',
    'akk' => 'аккадська',
    'ale' => 'алеутська',
    'alg' => 'алгонкінські мови',
    'alt' => 'південноалтайська',
    'am' => 'амхарська',
    'an' => 'арагонська',
    'ang' => 'давньоанглійська',
    'anp' => 'ангіка',
    'apa' => 'апачі мови',
    'ar' => 'арабська',
    'arc' => 'арамейська',
    'arn' => 'арауканська',
    'arp' => 'арапахо',
    'art' => 'штучна мова',
    'arw' => 'аравакська',
    'as' => 'ассамська',
    'asa' => 'Асу',
    'ast' => 'астурська',
    'ath' => 'атапаскські мови',
    'aus' => 'австралійськ